INSERT INTO interns (ID, NAME, SURNAME, AMOUNT) VALUES (1, 'Pepe', 'Perez', 1000.00);
INSERT INTO interns (ID, NAME, SURNAME, AMOUNT) VALUES (2, 'Juan', 'Lama', 1200.00);
INSERT INTO interns (ID, NAME, SURNAME, AMOUNT) VALUES (3, 'Sancho', 'Ramos', 1100.00);